---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: payment-state
  labels:
    run: payment-state
spec:
  replicas: 3
  selector:
    matchLabels:
      run: payment-state
  template:
    metadata:
      creationTimestamp:
      labels:
        run: payment-state
    spec:
      containers:
      - name: payment-state
        image: payment-state:v1
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: payment-state
  labels:
    run: payment-state
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30172
  selector:
    run: payment-state
  type: LoadBalancer
